=== dementrock/pygame/doc/src/api.dtd
<!DOCTYPE module [
<!ELEMENT module (alias?, short, desc, example?, (func | class)*)>
<!ATTLIST module name CDATA #REQUIRED>

<!ELEMENT alias (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT short (#PCDATA)>
<!ELEMENT call (#PCDATA)>

<!ELEMENT func (call, desc, example?)>
<!ATTLIST func name CDATA #REQUIRED>

<!ELEMENT class (constructor, desc, example?, (attr | method)*)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT constructor (#PCDATA)>

<!ELEMENT attr (desc, example?)>
<!ATTLIST attr name CDATA #REQUIRED>

<!ELEMENT method (call, desc, example*)>
<!ATTLIST method name CDATA #REQUIRED>

]>

=== dementrock/pygame/doc/src/sdlmixerchannel.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlmixer.channel">
  <short>SDL_mixer sound channel handling</short>
  <desc></desc>

  <func name="allocate">
    <call></call>
    <desc></desc>
  </func>
  <func name="expire">
    <call></call>
    <desc></desc>
  </func>
  <func name="fade_out">
    <call></call>
    <desc></desc>
  </func>
  <func name="get_volume">
    <call></call>
    <desc></desc>
  </func>
  <func name="halt">
    <call></call>
    <desc></desc>
  </func>
  <func name="opened">
    <call></call>
    <desc></desc>
  </func>
  <func name="pause">
    <call></call>
    <desc></desc>
  </func>
  <func name="paused">
    <call></call>
    <desc></desc>
  </func>
  <func name="playing">
    <call></call>
    <desc></desc>
  </func>
  <func name="resume">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_volume">
    <call></call>
    <desc></desc>
  </func>
</module>

=== dementrock/pygame/doc/src/mathbase.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.math.base">
  <show>0</show>
  <alias>pygame2.math</alias>
  <short>Vector math module for Pygame2</short>
  <desc>
    Vector math module for Pygame2
  </desc>
  <func name="vector_from_polar">
    <call>vector_from_polar (p1, p2) -> Vector2</call>
    <desc></desc>
  </func>
  <func name="vector_from_spherical">
    <call>vector_from_spherical (p1, p2, p3) -> Vector2</call>
    <desc></desc>
  </func>

  <class name="Vector">
    <constructor>Vector () -> Vector</constructor>
    <desc>Creates a new Vector.
    </desc>
    <attr name="dimension">
      <desc>Gets the dimensions of the :class:`Vector`.</desc>
    </attr>
    <attr name="length">
      <desc>Gets the length of the :class:`Vector`.</desc>
    </attr>
    <attr name="length_squared">
      <desc>Gets the length of the :class:`Vector`.</desc>
    </attr>
    <attr name="epsilon">
      <desc>Gets or sets the exactness delta of the :class:`Vector`.</desc>
    </attr>
    <attr name="elements">
      <desc>Gets or sets the elements of the :class:`Vector`.
    
      This will only set a maximum of :attr:`dimension` values.
      </desc>
    </attr>
    <attr name="normalized">
      <desc>Gets whether the :class:`Vector` is normalized.</desc>
    </attr>
    <method name="normalize">
      <call>normalize () -> Vector</call>
      <desc></desc>
    </method>
    <method name="normalize_ip">
      <call>normalize_ip () -> None</call>
      <desc></desc>
    </method>
    <method name="slerp">
      <call>slerp () -> Vector</call>
      <desc></desc>
    </method>
    <method name="lerp">
      <call>lerp () -> Vector</call>
      <desc></desc>
    </method>
    <method name="dot">
      <call>dot () -> float</call>
      <desc></desc>
    </method>
    <method name="scale_to">
      <call>scale_to (v) -> Vector</call>
      <desc></desc>
    </method>
    <method name="reflect">
      <call>reflect () -> Vector</call>
      <desc></desc>
    </method>
    <method name="reflect_ip">
      <call>reflect_ip () -> None</call>
      <desc></desc>
    </method>
    <method name="distance">
      <call>distance () -> None</call>
      <desc></desc>
    </method>
    <method name="distance_squared">
      <call>distance_squared () -> None</call>
      <desc></desc>
    </method>
  </class>
  
  <class name="Vector2">
    <constructor>Vector2 () -> Vector2</constructor>
    <desc>Creates a new Vector2.
    
      A simple 2D vector containing only two elements.
    </desc>
    <attr name="dimension">
      <desc>Gets the dimensions of the :class:`Vector2`.</desc>
    </attr>
    <attr name="elements">
      <desc>Gets or sets the elements of the :class:`Vector2`.
    
        This will only set a maximum of two values.
      </desc>
    </attr>
    <attr name="x">
      <desc>Gets or sets first element of the :class:`Vector2`.</desc>
    </attr>
    <attr name="y">
      <desc>Gets or sets second element of the :class:`Vector2`.</desc>
    </attr>
    <method name="rotate">
      <call>rotate () -> Vector2</call>
      <desc></desc>
    </method>
    <method name="rotate_ip">
      <call>rotate_ip () -> Vector2</call>
      <desc></desc>
    </method>
    <method name="as_polar">
      <call>as_polar () -> float, float</call>
      <desc></desc>
    </method>
    <method name="angle_to">
      <call>angle_to (v) -> float</call>
      <desc></desc>
    </method>
    <method name="cross">
      <call>cross (v) -> Vector2</call>
      <desc></desc>
    </method>
  </class>

  <class name="Vector3">
    <constructor>Vector3 () -> Vector3</constructor>
    <desc>Creates a new Vector3.
    
      A simple 3D vector containing only three elements.
    </desc>
    <attr name="dimension">
      <desc>Gets the dimensions of the :class:`Vector3`.</desc>
    </attr>
    <attr name="elements">
      <desc>Gets or sets the elements of the :class:`Vector3`.
    
        This will only set a maximum of three values.
      </desc>
    </attr>
    <attr name="x">
      <desc>Gets or sets first element of the :class:`Vector3`.</desc>
    </attr>
    <attr name="y">
      <desc>Gets or sets second element of the :class:`Vector3`.</desc>
    </attr>
    <attr name="z">
      <desc>Gets or sets third element of the :class:`Vector3`.</desc>
    </attr>
    <method name="rotate_x">
      <call>rotate_x () -> Vector3</call>
      <desc></desc>
    </method>
    <method name="rotate_x_ip">
      <call>rotate_x_ip () -> None</call>
      <desc></desc>
    </method>
    <method name="rotate_y">
      <call>rotate_y () -> Vector3</call>
      <desc></desc>
    </method>
    <method name="rotate_y_ip">
      <call>rotate_y_ip () -> None</call>
      <desc></desc>
    </method>
    <method name="rotate_z">
      <call>rotate_z () -> Vector3</call>
      <desc></desc>
    </method>
    <method name="rotate_z_ip">
      <call>rotate_z_ip () -> None</call>
      <desc></desc>
    </method>
    <method name="rotate">
      <call>rotate () -> Vector3</call>
      <desc></desc>
    </method>
    <method name="rotate_ip">
      <call>rotate_ip () -> Vector3</call>
      <desc></desc>
    </method>
    <method name="angle_to">
      <call>angle_to (v) -> float</call>
      <desc></desc>
    </method>
    <method name="cross">
      <call>cross (v) -> Vector3</call>
      <desc></desc>
    </method>
    <method name="as_spherical">
      <call>as_spherical () -> float, float, float</call>
      <desc></desc>
    </method>
  </class>

</module>

=== dementrock/pygame/doc/src/sdlmixermusic.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlmixer.music">
  <short>SDL_mixer music playback</short>
  <desc></desc>

  <func name="fade_out">
    <call></call>
    <desc></desc>
  </func>
  <func name="fading">
    <call></call>
    <desc></desc>
  </func>
  <func name="get_volume">
    <call></call>
    <desc></desc>
  </func>
  <func name="halt">
    <call></call>
    <desc></desc>
  </func>
  <func name="pause">
    <call></call>
    <desc></desc>
  </func>
  <func name="paused">
    <call></call>
    <desc></desc>
  </func>
  <func name="playing">
    <call></call>
    <desc></desc>
  </func>
  <func name="resume">
    <call></call>
    <desc></desc>
  </func>
  <func name="rewind">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_position">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_volume">
    <call></call>
    <desc></desc>
  </func>
</module>

=== dementrock/pygame/doc/src/freetypebase.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.freetype.base">
  <alias>pygame2.freetype</alias>
  <short>Wrapping module for the FreeType 2 font library</short>
  <desc>
    This module wraps the FreeType 2 font library to add improvent font
    drawing capabilities to PyGame2, such as new font formats, etc.
  </desc>
  <func name="get_error">
    <call>get_version () -> (int, int, int)</call>
    <desc>
        Returns the description of the last error which occurred in the
        FreeType library, or None if no error have occurred.
    </desc>
  </func>

  <func name="get_version">
    <call>get_version () -> (int, int, int)</call>
    <desc>
        Gets the version of the FreeType2 library which was used to build
        the 'freetype' module.
    </desc>
  </func>
  <func name="init">
    <call>init () -> None</call>
    <desc>
      Initializes the underlying FreeType 2 library.
      
      This method must be called before trying to use any of the functionality
      of the 'freetype' module.
    </desc>
  </func>
  <func name="quit">
    <call>quit () -> None</call>
    <desc>
      Shuts down the underlying FreeType 2 library.

      After calling this function, you should not invoke any class,
      method or function related to the 'freetype' module as they are likely to
      fail or might give unpredictable results.
    </desc>
  </func>
  <func name="was_init">
    <call>was_init () -> bool</call>
    <desc>
      Returns whether the the FreeType 2 library is initialized.
    </desc>
  </func>


  <class name="Font">
    <constructor>Font (file [, ptsize, index]) -> Font</constructor>
    <desc>
        Creates a new Font from a supported font file.

        *file* can be either a string representing the font's filename or
        a file-like object containing the font.

        Optionally, a *ptsize* argument may be specified to set the
        default size in points which will be used to render the font. 
        Such size can also be specified manually on each method call.
        Because of the way the caching system works, specifying a
        default size on the constructor doesn't imply a performance
        gain over manually passing the size on each function call.

        If the font file has more than one face, the *index* argument
        may be specified to specify which face index to load. Defaults
        to 0; font loading will fail if the given index is not contained
        in the font.
    </desc>
    <attr name="name">
      <desc>Gets the name of the font face.</desc>
    </attr>
    <method name="get_size">
      <call>get_size(text [, ptsize]) -> int, int</call>
      <desc>
          Gets the size in pixels which 'text' will occupy when rendered using 
          this Font.

          Returns a tuple containing the width and height of the text's
          bounding box. 
          
          The calculations are done using the font's default size in points.
          Optionally you may specify another point size to use.
      </desc>
    </method>
    <method name="get_metrics">
      <call>get_metrics(text, [bbmode, ptsize]) -> [(...), ...]</call>
      <desc>
        Returns the glyph metrics for each character in 'text'.

        The glyph metrics are returned inside a list; each character will
        be represented as a tuple inside the list with the following values:

          (min_x, max_x, min_y, max_y, horizontal_advance)

        By default, these values are returned as grid-fitted pixel
        coordinates (ints). Optionally, one of the following constants
        (which can be found on the FreeType constants module) may be passed
        as the bbmode argument:

            BBOX_EXACT: Return accurate floating point values.

            BBOX_EXACT_GRIDFIT: Return accurate floating point values aligned
            to the drawing grid.

            BBOX_PIXEL: Return pixel coordinates (ints).

            BBOX_PIXEL_GRIDFIT (default): Return grid-aligned pixel coordinates.
        
        The calculations are done using the font's default size in points.
        Optionally you may specify another point size to use.

      </desc>
    </method>
    <attr name="height">
      <desc>Gets the height of the Font.</desc>
    </attr>
    <method name="render">
      <call>render(text, fgcolor[, bgcolor, dstsurface, xpos, ypos, ptsize]) -> (int, int, :class:`pygame2.sdl.video.Surface`)</call>
      <desc>
        Renders a text on a SDL surface.

        Renders the string *text* to a
        :class:`pygame2.sdl.video.Surface`, using the color *fgcolor*.

        If a destination surface *dstsurface*' exists and is a
        :class:`pygame2.sdl.video.Surface` (independently of its bit
        depth), the text will be rendered directly on top of it at the
        passed coordinates (*xpos*, *ypos*). The width and height of
        the rendered text as well as the surface will be returned in a
        tuple.

        If there is no destination surface, a new
        :class:`pygame2.sdl.video.Surface` will be created with the
        required size to contain the drawn text, using *bgcolor* as its
        background color. The width and height of the rendered text,
        together with the new :class:`pygame2.sdl.video.Surface`, will
        be returned in a tuple.

        The rendering is done using the font's default size in points.
        Optionally you may specify another point size to use.

        This function is only available when PyGame 2 has been compiled
        with SDL support.
      </desc>
    </method>
    <method name="render_raw">
      <call>render_raw(text [, ptsize]) -> (int, int, bytes)</call>
      <desc>
        Renders a text to a byte buffer.

        Renders the string *text* to a raw buffer of bytes, each byte
        representing the opacity of the glyph's raster image in
        grayscale.
        
        The width (pitch) and height of the rendered text, together with
        the bytes buffer, will be returned in a tuple.

        The rendering is done using the font's default size in points.
        Optionally you may specify another point size to use.
      </desc>
    </method>
    <attr name="style">
      <desc>Gets or sets the style of the Font.
      
      .. todo::
      
        TODO
      </desc>
    </attr>
    <attr name="fixed_width">
      <desc>
        Returns whether this Font is a fixed-width (bitmap) font.
        
        .. note::
        
          Note that scalable fonts whose glyphs are all the same width 
          (i.e. monospace TTF fonts used for programming) are not considered
          fixed width.
      </desc>
    </attr>
  </class>
  
</module>

=== dementrock/pygame/doc/src/sdlimage.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.image">
  <short>SDL image I/O wrapper module</short>
  <desc>SDL image I/O wrapper module</desc>

  <func name="load_bmp">
    <call>load_bmp (file) -> :class:`pygame2.sdl.video.Surface`</call>
    <desc>Loads a BMP file and creates a :class:`pygame2.sdl.video.Surface` from it.
    
      Loads a BMP file and creates a :class:`pygame2.sdl.video.Surface` from it.
      The file argument can be either a file object or the filename.
    </desc>
  </func>
  <func name="save_bmp">
    <call>save_bmp (surface, file) -> None</call>
    <desc>Saves a surface to a bitmap file.

      Saves a :class:`pygame2.sdl.video.Surface` to the specified file, where
      file can be a filename or file object.
    </desc>
  </func>
</module>
