<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module [
<!ELEMENT module (desc, (func|class)*)>
<!ATTLIST module name CDATA #REQUIRED>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT func (desc)>
<!ATTLIST func name CDATA #REQUIRED>
<!ELEMENT class (constructor, desc, (attr|method)*)>
<!ATTLIST class name CDATA #REQUIRED>
<!ELEMENT constructor (#PCDATA)>
<!ELEMENT attr (#PCDATA)>
<!ATTLIST attr name CDATA #REQUIRED>
<!ELEMENT method (desc)>
<!ATTLIST method name CDATA #REQUIRED>
]>

<module name="pygame2.sdlext.transform">
  <desc></desc>

  <func name="average_color">
    <desc></desc>
  </func>
  <func name="average_surfaces">
    <desc></desc>
  </func>
  <func name="chop">
    <desc></desc>
  </func>
  <func name="flip">
    <desc></desc>
  </func>
  <func name="laplacian">
    <desc></desc>
  </func>
  <func name="rotate">
    <desc></desc>
  </func>
  <func name="scale">
    <desc></desc>
  </func>
  <func name="scale2x">
    <desc></desc>
  </func>
  <func name="smoothscale">
    <desc></desc>
  </func>
  <func name="threshold">
    <desc></desc>
  </func>
</module>

