<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module [
<!ELEMENT module (desc, (func|class)*)>
<!ATTLIST module name CDATA #REQUIRED>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT func (desc)>
<!ATTLIST func name CDATA #REQUIRED>
<!ELEMENT class (constructor, desc, (attr|method)*)>
<!ATTLIST class name CDATA #REQUIRED>
<!ELEMENT constructor (#PCDATA)>
<!ELEMENT attr (#PCDATA)>
<!ATTLIST attr name CDATA #REQUIRED>
<!ELEMENT method (desc)>
<!ATTLIST method name CDATA #REQUIRED>
]>

<module name="pygame2.sdl.gl">
  <desc></desc>

  <func name="get_attribute">
    <desc></desc>
  </func>
  <func name="get_proc_address">
    <desc></desc>
  </func>
  <func name="load_library">
    <desc></desc>
  </func>
  <func name="set_attribute">
    <desc></desc>
  </func>
  <func name="swap_buffers">
    <desc></desc>
  </func>
</module>

