<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module [
<!ELEMENT module (desc, (func|class)*)>
<!ATTLIST module name CDATA #REQUIRED>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT func (desc)>
<!ATTLIST func name CDATA #REQUIRED>
<!ELEMENT class (constructor, desc, (attr|method)*)>
<!ATTLIST class name CDATA #REQUIRED>
<!ELEMENT constructor (#PCDATA)>
<!ELEMENT attr (#PCDATA)>
<!ATTLIST attr name CDATA #REQUIRED>
<!ELEMENT method (desc)>
<!ATTLIST method name CDATA #REQUIRED>
]>

<module name="pygame2.sdl.time">
  <desc></desc>

  <func name="add_timer">
    <desc></desc>
  </func>
  <func name="delay">
    <desc></desc>
  </func>
  <func name="get_ticks">
    <desc></desc>
  </func>
  <func name="init">
    <desc></desc>
  </func>
  <func name="quit">
    <desc></desc>
  </func>
  <func name="remove_timer">
    <desc></desc>
  </func>
  <func name="set_timer">
    <desc></desc>
  </func>
  <func name="was_init">
    <desc></desc>
  </func>
</module>

